# Snakemake configuration file
#
# The variables in this file control the behavior of the Snakefile at the root
# of the project. It starts with raw sequencing reads in FASTQ files and
# converts them to gene counts.

# Paths ------------------------------------------------------------------------

# The following paths must be updated to run the scripts on your machine.

# Paths must end with forward slash

# Enter the absolute path to the local directory to store the final data files
dir_data: /home/jdblischak/singlecell-qtl/data/

# Enter the absolute path to a scratch directory for writing temporary files
dir_scratch: /scratch/midway2/jdblischak/

# Enter the absolute path to an external directory to store intermediate files.
# It should also contain a subdirectory fastq/ which contains the raw gzipped
# FASTQ files.
dir_external: /project2/gilad/singlecell-qtl/

# Enter the path (absolute or relative to the Snakefile) for writing log
# files. Make sure to also update this path for log files in cluster.json
dir_log: log/

# Samples ---------------------------------------------------------------------

# Select which samples to run. You should select a subset when first configuring
# and testing the pipeline.

# C1 chips
chips: ["03162017", "03172017", "03232017", "03302017", "03312017",
        "04052017", "04072017", "04132017", "04142017", "04202017",
        # batch 2
        "08102017", "08112017", "08142017", "08152017", "08162017",
        "08182017", "08212017", "08222017", "08232017", "08242017",
        "08282017", "08292017", "08302017", "08312017"]

# rows of chips
rows: ["A", "B", "C", "D", "E", "F", "G", "H"]

# columns of chips
cols: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]

# Annotation -------------------------------------------------------------------

# The following variables control which genome release is used for annotation
# and which chromosomes are considered.

# Specify Ensembl release for genome sequence and annotation
# http://feb2014.archive.ensembl.org/index.html
ensembl_archive: feb2014.archive.ensembl.org
ensembl_rel: 75
ensembl_genome_ce: WBcel235.75
ensembl_genome_dm: BDGP5.75
ensembl_genome_hs: GRCh37.75

chr_ce: ["I", "II", "III", "IV", "V", "X", "MtDNA"]
chr_dm: ["2L", "2R", "3L", "3R", "4", "dmel_mitochondrion_genome", "X", "YHet"]
chr_hs: ["1", "2", "3", "4", "5", "6", "7", "8", "9",
         "10", "11", "12", "13", "14", "15", "16",
         "17", "18", "19", "20", "21", "22",
         "X", "Y", "MT"]
