# Conda configuration file to reproduce computing environment
#
# Instructions
# 1. Create the conda environment:
#    conda env create --file environment.yaml
#
# 2. Update the conda environment:
#    conda env update --file environment.yaml
#
# 3. Activate the conda environment:
#    source activate fucci-seq
#
# 4. Deactivate the conda environment:
#    source deactivate fucci-seq
#
# Resources:
#
# https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand
# https://bioconda.github.io
# https://anaconda.org/jdblischak/repo
#
# Tips:
# 1. Create custom channels in anaconda. The purpose of doing this is to
#    maintain a stable release of all software packages used in this project.
#
#
name: fucci-seq
channels:
  - jdblischak
  - bioconda
  - conda-forge
  - defaults
  - r

dependencies:
  - bioconductor-biobase
  - bioconductor-biocinstaller
  - bioconductor-biomart
  - bioconductor-deseq2 
  - bioconductor-ebimage
  - bioconductor-edger
  - bioconductor-scran
  - biopython
  - docopt
  - fastqc
  - git
  - git-lfs
  - glpk
  - ipdb
  - ipython
  - multiqc
  - pandoc==1.19.2
  - pysam
  - python
  - pysftp
  - r-base==3.4.1
  - r-ccremover
  - r-cellcycler 
  - r-circular
  - r-cluster
  - r-ccremover
  - r-conicfit
  - r-cowplot
  - r-data.table
  - r-dplyr
  - r-dt
  - r-gdata
  - r-genlasso
  - r-ggplot2
  - r-gplots
  - r-heatmap3
  - r-lpsolve
  - r-mclust
  - r-scales
  - r-rcolorbrewer
  - r-reshape2
  - r-stringr
  - r-testit
  - r-tidyr
  - r-venndiagram
  - r-wesanderson
  - r-workflowr
  - samtools
  - snakemake
  - subread
  - umi_tools
  - verifybamid
  - wget
