---
title: "License"
output:
  workflowr::wflow_html:
    toc: false
---

The code is available under the [MIT license][mit]. The text, data, and figures
are available under the [CC-BY license][cc-by]. Please see the file
[LICENSE][license] for the full license text.

Both of these allow you to reuse, adapt, or redistribute the content as long as
you attribute us. If you use our data, please attribute us as follows:

> The single-cell RNA-seq data and FUCCI imaging data were generated by the
> Gilad lab at the University of Chicago (see
> https://github.com/jdblischak/fucci-seq for details).

If you use our code, please attribute us as follows:

> The code used to process the single-cell RNA-seq data was adapted from the
> code written by the [Gilad lab](gilad-lab) and the [Stephens
> lab](stephens-lab) at the University of Chicago (see
> https://github.com/jdblischak/fucci-seq for details).

For academic publications, please cite our published paper:

> Hsiao CJ, Tung P, Blischak JD, Burnett JE, Barr KA, Dey KK, Stephens M, Gilad
> Y. Characterizing and inferring quantitative cell cycle phase in single-cell
> RNA-seq data analysis. Genome Research. Cold Spring Harbor Laboratory; 2020
> Apr;30(4):611–621. Available from: http://dx.doi.org/10.1101/gr.247759.118

You can find a BibTeX entry for the above citation in [CITATION][citation].

[cc-by]: https://creativecommons.org/licenses/by/4.0/
[citation]: https://github.com/jdblischak/fucci-seq/blob/master/CITATION
[license]: https://github.com/jdblischak/fucci-seq/blob/master/LICENSE
[mit]: https://choosealicense.com/licenses/mit/
[gilad-lab]: http://giladlab.uchicago.edu/
[stephens-lab]: http://stephenslab.uchicago.edu/
