---
title: "Compares gene annotations between two different cell time types"
author: "Joyce Hsiao"
output: 
  html_document:
    toc: TRUE
    toc_float: FALSE
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning=FALSE)
```

---

## Goals

Consider top X cyclical genes, check GO categories. 

---

## Retrieve gene lists

```{r, eval=F}
genes_list <- readRDS(file = "../data/results/results_topgenes.rds")
genes_list_triple <- readRDS(file = "../data/results/triple_results_topgenes.rds")

all_genes <- genes_list[length(genes_list)][[1]]

library(biomaRt)
ensembl <- useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")
symbols <- getBM(attributes = c("hgnc_symbol",'ensembl_gene_id'), 
      filters = c('ensembl_gene_id'),
      values = all_genes, 
      mart = ensembl)

# get gene symbols for gene list under fucci cell time prediction
genes_list_symbols <- lapply(1:length(genes_list), function(i) {
  ll <- genes_list[i][[1]]
  #symbols[match(ll,symbols$ensembl_gene_id),]
  symbs <- symbols[which(symbols$ensembl_gene_id %in% ll),]
  non_symbs <- ll[which(!(ll %in% symbols$ensembl_gene_id))]
  df_non_symbs <- data.frame(hgnc_symbol=NA,
                             ensembl_gene_id=non_symbs)  
  out <- rbind(symbs, df_non_symbs)
  out <- out[match(ll,out$ensembl_gene_id),]
  return(out)
})
names(genes_list_symbols) <- names(genes_list)

# get gene symbols for gene list under fucci and dapi cell time prediction
genes_list_symbols_triple <- lapply(1:length(genes_list_triple), function(i) {
  ll <- genes_list_triple[i][[1]]
  #symbols[match(ll,symbols$ensembl_gene_id),]
  symbs <- symbols[which(symbols$ensembl_gene_id %in% ll),]
  non_symbs <- ll[which(!(ll %in% symbols$ensembl_gene_id))]
  if (length(non_symbs)==0) {
    out <- symbs    
  } 
  if (length(non_symbs)>0) {
    df_non_symbs <- data.frame(hgnc_symbol=NA,
                           ensembl_gene_id=non_symbs)  
    out <- rbind(symbs, df_non_symbs)
  }
  out <- out[match(ll,out$ensembl_gene_id),]
  return(out)
})
names(genes_list_symbols_triple) <- names(genes_list_triple)

saveRDS(genes_list_symbols, 
        "../output/method-train-genes-fucci-vs-triple.Rmd/genes_list_symbols.rds")
saveRDS(genes_list_symbols_triple, 
        "../output/method-train-genes-fucci-vs-triple.Rmd/genes_list_symbols_triple.rds")
```


---

## Overlap with Seurat genes

```{r}
genes_list <- readRDS(file = "../data/results/results_topgenes.rds")
genes_list_triple <- readRDS(file = "../data/results/triple_results_topgenes.rds")
genes_list_symbols <- readRDS("../output/method-train-genes-fucci-vs-triple.Rmd/genes_list_symbols.rds")
genes_list_symbols_triple <- readRDS("../output/method-train-genes-fucci-vs-triple.Rmd/genes_list_symbols_triple.rds")

seurat.genes <- readLines(
  con = "../data/cellcycle-genes-previous-studies/seurat_cellcycle/regev_lab_cell_cycle_genes.txt")
seurat.genes <- list(s.genes=seurat.genes[1:43],
                     g2m.genes=seurat.genes[44:97])


double_overlap  <- sapply(genes_list_symbols, function(x) sum(x$hgnc_symbol %in% unlist(seurat.genes)))
triple_overlap  <- sapply(genes_list_symbols_triple, function(x) sum(x$hgnc_symbol %in% unlist(seurat.genes)))

par(mfrow=c(1,2))
plot(x=names(genes_list)[1:40],
     sapply(genes_list, length)[1:40], 
     xlab="Top X cyclical genes",
     ylab="Number of selected genes",
     main = "Up to top 400")
points(x=names(genes_list_triple)[1:40],
          sapply(genes_list_triple, length)[1:40], col="blue", pch=1)
legend("topleft", pch=1, col=c("black", "blue"),
       legend=c("fucci time", "fucci and dapi time"))
plot(x=names(genes_list)[1:11],
     sapply(genes_list, length)[1:11], 
     xlab="Top X cyclical genes",
     ylab="Number of selected genes",
     main = "Up to to 100", ylim=c(0, 65))
points(x=names(genes_list_triple)[1:11],
          sapply(genes_list_triple, length)[1:11], col="blue", pch=1)


par(mfrow=c(1,2))
plot(x=names(genes_list)[1:40],
     double_overlap[1:40], 
     xlab="Top X cyclical genes",
     ylab="Number of Seurat genes (total 92 detected)",
     main = "Up to top 400", ylim=c(0,80))
points(x=names(genes_list_triple)[1:40],
          triple_overlap[1:40], col="blue", pch=1)
legend("topleft", pch=1, col=c("black", "blue"),
       legend=c("fucci time", "fucci and dapi time"))

plot(x=names(genes_list)[1:11],
     double_overlap[1:11], 
     xlab="Top X cyclical genes",
     ylab="Number of Seurat genes (total 92 detected)",
     main = "Up to top 100", ylim=c(0,30))
points(x=names(genes_list_triple)[1:11],
          triple_overlap[1:11], col="blue", pch=1)
```


---

## Save top 100 genes symbols to output table

```{r, eval=F}
write.table(genes_list_symbols[[11]]$hgnc_symbol,
            file = "../output/method-train-genes-fucci-vs-triple.Rmd/topgenes.txt",
            row.names=F,
            col.names=F, quote=F)

write.table(genes_list_symbols_triple[[11]]$hgnc_symbol,
            file = "../output/method-train-genes-fucci-vs-triple.Rmd/triple_topgenes.txt",
            row.names=F,
            col.names=F, quote=F)

write.table(genes_list_symbols[[length(genes_list_symbols)]][,1],
            file = "../output/method-train-genes-fucci-vs-triple.Rmd/allgenes.txt",
            row.names=F,
            col.names=F, quote=F)
```




---

## Session information

```{r}
sessionInfo()
```

