---
title: "Check gene annotation"
author: "Joyce Hsiao"
output: 
  workflowr::wflow_html:
    toc: TRUE
    toc_float: FALSE
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning=FALSE)
```

---

## Goals

Consider top X cyclical genes, check GO categories. 

---

## Retrieve gene lists

```{r, eval=F}
genes_list <- readRDS(file = "../data/results/results_topgenes.rds")
all_genes <- genes_list[length(genes_list)][[1]]

library(biomaRt)
ensembl <- useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")
symbols <- getBM(attributes = c("hgnc_symbol",'ensembl_gene_id'), 
      filters = c('ensembl_gene_id'),
      values = all_genes, 
      mart = ensembl)

genes_list_symbols <- lapply(1:length(genes_list), function(i) {
  ll <- genes_list[i][[1]]
  #symbols[match(ll,symbols$ensembl_gene_id),]
  symbs <- symbols[which(symbols$ensembl_gene_id %in% ll),]
  non_symbs <- ll[which(!(ll %in% symbols$ensembl_gene_id))]
  df_non_symbs <- data.frame(hgnc_symbol=NA,
                             ensembl_gene_id=non_symbs)  
  out <- rbind(symbs, df_non_symbs)
  out <- out[match(ll,out$ensembl_gene_id),]
  return(out)
})
names(genes_list_symbols) <- names(genes_list)

saveRDS(genes_list_symbols, 
        "../output/method-train-classifiers-genes.Rmd/genes_list_symbols.rds")
```


---

## Overlap with Seurat genes

```{r}
genes_list <- readRDS(file = "../data/results/results_topgenes.rds")
genes_list_symbols <- readRDS("../output/method-train-classifiers-genes.Rmd/genes_list_symbols.rds")

seurat.genes <- readLines(
  con = "../data/cellcycle-genes-previous-studies/seurat_cellcycle/regev_lab_cell_cycle_genes.txt")
seurat.genes <- list(s.genes=seurat.genes[1:43],
                     g2m.genes=seurat.genes[44:97])

tmp  <- sapply(genes_list_symbols, function(x) sum(x$hgnc_symbol %in% unlist(seurat.genes)))

par(mfrow=c(2,2))
plot(x=names(genes_list)[1:41],
     tmp[1:41], 
     xlab="Top X cyclical genes",
     ylab="Number of Seurate genes (total 97)",
     main = "Seurat genes in top 400")
plot(x=names(genes_list)[1:41],
     (tmp/as.numeric(names(genes_list)))[1:41], 
     xlab="Top X cyclical genes",
     ylab="Proportion of Seurate genes",
     main = "Seurat genes in top 400")
barplot(tmp[1:21],
        ylim=c(0,36),
        xlab="Top X cyclical genes",
        ylab="Number of selected genes")

print(tmp[1:21])
# library(gplots)
# venn(list(seurat=unlist(seurat.genes),
#           peco=genes_list_symbols[[27]]$hgnc_symbol))

```


---

## save to output table

```{r, eval=F}
write.table(genes_list_symbols[[11]]$hgnc_symbol,
            file = "../output/method-train-classifiers-genes.Rmd/topgenes.txt",
            row.names=F,
            col.names=F, quote=F)

write.table(genes_list_symbols[[length(genes_list_symbols)]][,1],
            file = "../output/method-train-classifiers-genes.Rmd/allgenes.txt",
            row.names=F,
            col.names=F, quote=F)
```




---


```{r}
sessionInfo()
```

